### ISSUE TITLE
Support for new Artifactory & Quay Perceivers

### ISSUE THREAD

**Issue by gautambaghel** [blackducksoftware/synopsys-operator#1005]
**What would you like to be added**: #1000 Commands & resource to deploy the new perceivers

**Why is this needed**: Customers use Quay and Artifactory for storing their images

**Comment by gautambaghel** [comment]
https://jira.dc1.lan/browse/OPSSIGHT-541
https://jira.dc1.lan/browse/OPSSIGHT-542

**Comment by yashbhutwala** [comment]
Resolved in #1092; cherry-picked in #1106
