### ISSUE TITLE
2019.8.4 --enable-binary-analysis flag does not work when --environs specified

### ISSUE THREAD

**Issue by nichollsdave** [blackducksoftware/synopsys-operator#1033]
**What happened**:
When creating a blackduck either via native or Operator if you provide --enable-binary-analysis flag it does not add the binary analysis containers.  I have also tried --enable-binary-analysis=true and --template bdba but it does not add the containers.

**What you expected to happen**:
I expect to get the rabbitmq and binaryscanner containers etc in the deployment but they are not there.

**How to reproduce it (as minimally and precisely as possible)**:
./synopsysctl create blackduck native test --enable-binary-analysis --environs TEST:TEST  -o yaml > blackduck.yaml

**Environment (please complete the following information):**
- Kubernetes version (use `kubectl version`): 1.16.0
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu 
- Kernel (e.g. `uname -a`): Linux ip-172-31-46-116 4.15.0-1044-aws #46-Ubuntu SMP Thu Jul 4 13:38:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yashbhutwala** [comment]
@nichollsdave This is because the `--environs` inputs override the `--enable-binary-analysis` option.  Can you try it without the `--environs` option?

**Comment by yashbhutwala** [comment]
Fixed by #1036
