### ISSUE TITLE
Postgres not able to reclaim PV(Permission Denied) after cluster restart

### ISSUE THREAD

**Issue by subhamsps** [blackducksoftware/synopsys-operator#1042]
**What happened**:
Installed minikube on my VM (hostpath is the default dynamic provisioner in minikube)
Installed BD successfully using synopsysctl 
Restarted VM, postgres pod fails to start.

**What you expected to happen**:
BD up and running. Postgres pod in Running state

**How to reproduce it (as minimally and precisely as possible)**:
install postgress image and use hostpath as dynamic provisioner. Restart the system and postgres pod will not come up.
ERROR:
root@subham-pc:/home/subham# kubectl -n synopsys-operator logs bd-blackduck-postgres-bf798
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied

**Screenshots/additional context**:
creating /var/lib/pgsql/data/userdata manually and giving it chmod 777 permissons did not resolve the issue either. 
Seems to be a known issue with official postgres image.
https://access.redhat.com/solutions/3508731 (solution might be here but we need customer or partner access)

**Environment (please complete the following information):**
- Kubernetes version (use `kubectl version`):  Kubernetes v1.16.0 on Docker 19.03.3
- Openshift version (use `oc version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.10
- Kernel (e.g. `uname -a`): 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others: minikube v1.4.0

**Comment by yashbhutwala** [comment]
P.s. @subhamsps the redhat link that you gave does suggest `chmod 777` as the workaround

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5788514/67859362-d0e14f80-faf1-11e9-92ea-3e0641dea41b.png">

Here is their [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1402257).

**Comment by yashbhutwala** [comment]
@subhamsps as discussed in slack, this is because the `hostPath` provisioner in `minikube` does not schedule the pod on the same node as the pv.  This is more of an infrastructure issue, and not a deployment one.  

I would suggest not running in `minikube` and not using `hostPath` provisioner, especially for production setting.  Also, in production setting, I'd recommend using an out of cluster database.

For dev settings, I've been able to deploy in `kind` using rancher's `local-hostpath-provisioner` (which takes care of the node affinity scheduling) and using this setting through synopsysctl.

`./synopsysctl create blackduck bd --admin-password a --user-password u --postgres-password p --pvc-file-path=pvc.json --size small`

pvc.json

```json
[
    {
        "name": "blackduck-postgres",
        "size": "1Gi"
    },
    {
        "name": "blackduck-authentication",
        "size": "1Gi"
    },
    {
        "name": "blackduck-cfssl",
        "size": "1Gi"
    },
    {
        "name": "blackduck-logstash",
        "size": "1Gi"
    },
    {
        "name": "blackduck-zookeeper",
        "size": "1Gi"
    },
    {
        "name": "blackduck-registration",
        "size": "1Gi"
    },
    {
        "name": "blackduck-webapp",
        "size": "1Gi"
    },
    {
        "name": "blackduck-uploadcache-data",
        "size": "1Gi"
    },
    {
        "name": "blackduck-solr",
        "size": "1Gi"
    }
]
```

**Comment by yashbhutwala** [comment]
Btw here is the kind cluster settings I used: https://github.com/yashbhutwala/kind-hacks/blob/master/kind-multi-worker-cluster.yml

`kind create cluster --config ~/kind-hacks/kind-multi-worker-cluster.yml --image kindest/node:v1.16.2` 

`kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.11/deploy/local-path-storage.yaml`

`kubectl patch storageclass "local-path" -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'`

`kubectl delete storageclasses.storage.k8s.io standard`
