### ISSUE TITLE
Synopsys ctl doesn't check $KUBECONFIG

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#1046]
https://jira-sig.internal.synopsys.com/projects/CLOUD/issues/CLOUD-487

**Expected results**  
synopsysctl should be able to access the cluster and perform the operation since $KUBECONFIG is defined and is valid.

**Actual result**  
Synopsysctl fails because it only checks "~/.kube/config" and doesn't check $KUBECONFIG

**Comment by yashbhutwala** [comment]
Fixed by #1038 

Needs documentation
