### ISSUE TITLE
should not be creating pvc for solr after blackduck 2019.8.0

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#1052]
**What happened**:

- [ ] --output-pvc is still outputting solr even though we don't have it anymore

- [ ] should not be creating pvc for blackduck > 2019.8.0

- [ ] we still have this field in the blackduck-config configmap: HUB_SOLR_HOST: bd-blackduck-solr

https://github.com/blackducksoftware/synopsys-operator/blob/master/pkg/apps/blackduck/latest/containers/pvc.go#L35

**Comment by yashbhutwala** [comment]
Resolved by #1081 

@mphammer actually more fixes went in than what this ticket was asking, can you please add to the fixes added, to make it clear for release notes? 😃

**Comment by mphammer** [comment]
Fixed by #1098 and #1099
