### ISSUE TITLE
[in UI] Clarify which inputs are absolutely required for deploying Polaris

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#1066]
**What would you like to be added**:
Make it clear to the "deployer of Polaris" which fields are required to deploy.  This includes conditional requirements, for example if `postgres container` is used, only `postgres-password` is required.  if `postgres container` is not used, `postgres-host`, `postgres-port`, `postgres-username`, and `postgres-password` are required.

**Why is this needed**:
Better user experience

**Comment by mphammer** [comment]
The UI now has asterisks (*) next to fields that are required. Closed by PR #1084
