### ISSUE TITLE
review rbac permissions with regards to k8s api changes

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#1079]
**What would you like to be added**:

Audit this.

- [x] remove permissions not needed (specifically jobs, cronjobs, statefulsets)

- [x] update groups for k8s 1.16

https://github.com/blackducksoftware/synopsys-operator/blob/5bbc3d6138c8a6a8567bf949cb4bed301c4b244b/pkg/soperator/soperator_resources.go#L337

**Why is this needed**:

**Comment by msenmurugan** [comment]
tested against kube 1.9 and kube 1.15

**Comment by yashbhutwala** [comment]
Fixed by #1082
