### ISSUE TITLE
Add support for Black Duck 2019.10.1 and Alert 5.0.1

### ISSUE THREAD

**Issue by msenmurugan** [blackducksoftware/synopsys-operator#1096]
**What would you like to be added**:
Add support for Black Duck 2019.10.1 and Alert 5.0.1

**Comment by yashbhutwala** [comment]
Resolved by #1095 

need to manually cherry pick to master @msenmurugan

**Comment by yashbhutwala** [comment]
also, need to vendor operator to ui
