### ISSUE TITLE
inject HUB_SCAN_ALLOW_PARTIAL:true when BDBA is enabled

### ISSUE THREAD

**Issue by petergreen86** [blackducksoftware/synopsys-operator#1097]
`HUB_SCAN_ALLOW_PARTIAL:true` needs to be injected into the CM whenever `--enable-binary-analysis` is passed into a Black Duck deployment. 

This flag allows a partial match to be displayed if there is a clash between the mappings of the Protecode and Hub KBs. If this is not enabled, components get dropped from the BOM in Hub

**Comment by msenmurugan** [comment]
@petergreen86 discussed with Hub team about this feature. If we make it enable by default for all binary scan, then it will also affect the normal scan. So we won't implement this feature by default but in case if customer want to add this environment variables, then can use environs to set them. 

Please let me know whether I can close this ticket
