### ISSUE TITLE
2019.12.0 containers don't work as any user due to file permissions

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#1172]
Bug from #936, #972, jira-sig.internal.synopsys.com/browse/HUB-20580 and #1120

**What happened**:
web-app and potentially other 2019.12.0 hub containers don't work with securityContextChange because on each Docker entrypoint the container is hard-coded to do a chmod on certain files.

**What you expected to happen**:
Containers work as any user.

**Consensus Solution**:

These changes should make it work for all customers except for the ones that want to update uid/gid:

- [x] Revert changes to setting uid 1000 by default
- [x] Revert migrate
- [x] Remove comparison in crudupdater for security context
- [x] Don't do anything when the cluster is openshift

For customers wanting to pin uid/gid other than root:

- For customers using operator (editing cr with synopsysctl) logic goes in synopsysctl:

- [x] 1) Stop Hub (Scale down all deployments)
- [x] 2) Run Job per Persistent Volume to change permissions of needed volumes
- [ ] ~~3) Change CR --> (Operator takes care of changing the yaml of the deployment to include RunAsGroup and RunAsUser)~~
- [ ] 4) Start Hub (Scale up all deployments)

- for customers using native yaml or (manually editing the crd), manually execute these steps:

- [x] 1) Stop Hub (Scale down all deployments)
- [x] 2) Run Job per Persistent Volume to change permissions of needed volumes (provided in documentation or in code)
- [x] 3) Change yaml of new deployment either via synopsysctl create blackduck --native or manually or Change CR manually
- [x] 4) Apply the yaml

Good resource:
https://blog.openshift.com/jupyter-on-openshift-part-6-running-as-an-assigned-user-id/

**Comment by mphammer** [comment]
=== Docs ===
General Docs
1. Somewhere we should say that we do not support users directly editing the CR - they must always go through synopsysctl 

Security Contexts
1. Security Contexts is not supported in Openshift 
2. Security Contexts are only supported for BD versions 2019.12.0 and after
    1. For all Black Duck versions, by default the fsGroup is set to 0 in Kubernetes
3. Postgres needs to run as root or 26
Security Contexts with Synospys-Operator
1. Security Contexts with synopsys-operator
    1. Use the flag --set-security-context-file-path
2. Security Contexts with synopsys-operator if using Persistent Storage
    1. When security contexts are changed jobs will be run that change file ownership in each Persistent Volume to the RunAsUser value in SecurityContext field
    2. Changes to security contexts will not be applied if they are not done through synopsysctl (like by editing the CR directly)
Security Contexts with Native Mode
1. Security Contexts changes in Native Mode
    1. Use the flag --set-security-context-file-path
2. Security Contexts changes in Native Mode if using Persistent Storage 
    1. Step 1: Remove the Black Duck resources (and database if not external), but leave the persistent volumes
    2. Step 2: Run jobs that change ownership of files for each Persistent Volume
        1. Set the value 1000 to the ownership value
        2. You may need to remove jobs (ex: postgres job if you’re using an external database)
    3. Step 3: Deploy the Black Duck resources (and database if not external)


=== Tests Performed ===
GKE/Kubernetes
1. Update a 2019.10.1 to 2019.12.0 (no security contexts)
2. Update a 2019.10.1 to 2019.12.0 with security contexts
3. Update a 2019.10.1 to 2019.12.0 with security contexts AND persistent storage disabled
4. Create 2019.10.1 with security contexts -> error
5. Create 2019.12.0 (no security contexts)
6. Create 2019.12.0 with security contexts
7. Create 2019.12.0 with security contexts then change the security contexts
8. Create 2019.12.0 with security contexts then change the security contexts AND persistent storage disabled 
Openshift
1. Create 2019.12.0 (no security contexts)
2. Create 2019.12.0 with security contexts -> error
3. Create 2019.12.0 with security contexts then change the security contexts
Native
1. Create a 2019.10.0 Black Duck -> Delete everything except the PVs -> run jobs -> create 2019.12.0 resources (verify there are no permissions issues)

**Comment by yashbhutwala** [comment]
Resolved in release `2019.12.0`
