### ISSUE TITLE
Proposal: Use Go Plugins

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#144]
Instead of having all versions for all applications handled in the core of the operator, move the implementations for each application and possibly each application version to a plugin that can be loaded into the operator.

Plugins could be loaded through the UI or through synopsysctl for air-gapped customers, and for other customers the operator could d/l plugins from a central location.

**Comment by jbeakley** [comment]
we won't use go plugins... will consider other approaches.
