### ISSUE TITLE
synopsysctl panics if we don't pass any option

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#156]
### Environment
OCP 3.11
OSX 10.13.1

### Steps to reproduce
Execute `./synopsysctl`

### Expected behaviour
Synopsysctl prints the same output as `./synopsysctl --help`

### Actual  behaviour

> DEBU[0000] Getting Kube Rest Config
> ERRO[0000] error getting in cluster config. Fallback to native config. Error message: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
> DEBU[0000] oc exists and the cluster is openshift
> DEBU[0000] Running Non-Synopsysctl Command
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> github.com/blackducksoftware/synopsys-operator/pkg/util.RunKubeCmd(0xc000118c40, 0x100, 0xc0000ae000, 0x0, 0x0, 0xc000469cc8, 0x1c17ef4, 0xc000289d00, 0x2236ab4)
> 	/go/src/github.com/blackducksoftware/synopsys-operator/pkg/util/kubecmd.go:86 +0x345
> github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl.glob..func62(0x3137280, 0xc0000ae000, 0x0, 0x0, 0x0, 0x0)
> 	/go/src/github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl/cmd_root.go:58 +0xa6
> github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra.(*Command).execute(0x3137280, 0xc0000ae000, 0x0, 0x0, 0x3137280, 0xc0000ae000)
> 	/go/src/github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra/command.go:762 +0x473
> github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3137280, 0x14, 0xc000289200, 0x31374e0)
> 	/go/src/github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
> github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra.(*Command).Execute(0x3137280, 0x1005400, 0xc00008a058)
> 	/go/src/github.com/blackducksoftware/synopsys-operator/vendor/github.com/spf13/cobra/command.go:800 +0x2b
> github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl.Execute()
> 	/go/src/github.com/blackducksoftware/synopsys-operator/pkg/synopsysctl/cmd_root.go:71 +0x2d
> main.main()
> 	/go/src/github.com/blackducksoftware/synopsys-operator/cmd/synopsysctl/main.go:29 +0x20

**Comment by mphammer** [comment]
This issue was resolved in PR #168
