### ISSUE TITLE
synopsysctl shouldn't put anything inside imageRegistries

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#161]
**Describe the bug**
synopsysctl put the populate imageRegistries for new Blackduck instances

**Environment (please complete the following information):**
 - Openshift Version:  OCP 3.11

**To Reproduce**
`synopsysctl create blackduck test`
then
`oc get blackduck test -o yaml`

**Expected behavior**
imageRegistries is empty

**Actual behavior**
>  imageRegistries:
>   - docker.io/blackducksoftware/blackduck-authentication:2018.12.2
>   - docker.io/blackducksoftware/blackduck-documentation:2018.12.2
>   - docker.io/blackducksoftware/blackduck-jobrunner:2018.12.2
>   - docker.io/blackducksoftware/blackduck-registration:2018.12.2
>   - docker.io/blackducksoftware/blackduck-scan:2018.12.2
>   - docker.io/blackducksoftware/blackduck-webapp:2018.12.2
>   - docker.io/blackducksoftware/blackduck-cfssl:1.0.0
>   - docker.io/blackducksoftware/blackduck-logstash:1.0.2
>   - docker.io/blackducksoftware/blackduck-nginx:1.0.0
>   - docker.io/blackducksoftware/blackduck-solr:1.0.0
>   - docker.io/blackducksoftware/blackduck-zookeeper:1.0.0

**Comment by mphammer** [comment]
Fixed by PR #167
