### ISSUE TITLE
synopsysctl is missing a flag for the auth custom CA configuration

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#164]
**Describe the bug**
Synopsysctl is missing a flag for the configuration of spec.authCustomCa

**Environment (please complete the following information):**
 - Openshift Version:  OCP 3.11

**To Reproduce**
`synopsysctl create blackduck --help`

**Expected behavior**
A --auth-custom-ca  is in the list of flags

**Actual behavior**
No flag can be used to configure this.

**Comment by mphammer** [comment]
Fixed by PR #166
