### ISSUE TITLE
Exposing the service for opssight gets automatically deleted

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#165]
**Describe the bug**
Exposing a loadbalancer for opssight gets automatically deleted

**Environment:**
 - GKE - v1.11.7-gke.12

**To Reproduce**
1. `kc expose -n ops service prometheus --name=prometheus-lb --type=LoadBalancer`
2. `watch kc get svc -n ops`
3. The external ip is assigned, and then the service is deleted

**Expected behavior**
Service should stay

**Actual behavior**
Service is deleted

**Screenshots/additional context**
Current workaround is after deploying the service, manually go in, edit the service to remove the labels.
`kc edit service -n ops prometheus-lb`

**Comment by rrati** [comment]
Fixed
