### ISSUE TITLE
Support generating yaml for a deployment instead of just the CRD

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#170]
**Is your feature request related to a problem? Please describe.**
Some users might need to deploy an application w/o using the operator itself.  In highly secure environments a user might be given access to a namespace and no other permissions, even the internal kubernetes API.

**Describe the solution you'd like**
A way for synopsysctl to generate the deployment yaml that the operator would use.  Currently it can create the yaml that would be used for the CRD, but in this case that would not be sufficient.

**Comment by mphammer** [comment]
Issue implemented by PR #383
