### ISSUE TITLE
[synopsysctl] --expose-service should have "openshift" in the list of values

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#171]
**Describe the bug**
The synsopsysctl help only shows list [Loadbalancer/Nodeport] as valid parameters for --expose-service

**To Reproduce**
`synopsysctl create blackduck --help`

**Expected behavior**
The valid values should be:
- Loadbalancer
- NodePort
- Openshift

**Actual behavior**
Only Loadbalancer and Nodeport are listed

**Comment by mphammer** [comment]
Fixed by PR #166
