### ISSUE TITLE
Add Mock for Synopsysctl Deploy and Update

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#203]
**Describe the solution you'd like**
Allow the user to use the --mock flag when deploying the operator in order to see the configuration without actually deploying it into the cluster.

**Comment by mphammer** [comment]
I think it would be useful to also have --mock for modifying resources. Then the user can see what the changes will look like before they are actually performed.

**Comment by mphammer** [comment]
Maybe also add --mock flag that is a boolean and defaults to printing in json. And an --fmock=format flag that lets you specify the format of the output (json, yaml).

**Comment by yashbhutwala** [comment]
> Maybe also add --mock flag that is a boolean and defaults to printing in json. And an --fmock=format flag that lets you specify the format of the output (json, yaml).

Why do we need two flags?  Why can't it just be the `--mock` flag, with `json` as default and as optional a user can pass in?

**Comment by mphammer** [comment]
> > Maybe also add --mock flag that is a boolean and defaults to printing in json. And an --fmock=format flag that lets you specify the format of the output (json, yaml).
> 
> Why do we need two flags? Why can't it just be the `--mock` flag, with `json` as default and as optional a user can pass in?

When flags have default values it means that if they are not set then synopsysctl will use a default value as if they were set. However, for mock mode, you must set a flag to tell it to use mock mode, thus you must provide a value. The flag can be a Boolean Flag that does not need a value explicitly entered or a String Flag that needs a value explicitly entered, but it cannot be both.

**Comment by mphammer** [comment]
Issue implemented by PR #383
