### ISSUE TITLE
Alert Team Supports Custom Host Name in Certificate

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#206]
**Is your feature request related to a problem? Please describe.**
Allow people to pass custom host names for certificate authentication.   

Then we can allow certificate authentication for the alert server when running in StandAlone=false and in a different namespace than the Black Duck. 

**Solution**   
Add another --san to https://github.com/blackducksoftware/blackduck-alert/blob/master/docker-entrypoint.sh .

**Comment by jdartigalongue** [comment]
It looks like we can already set HUB_WEBAPP_HOST
