### ISSUE TITLE
Support starting Hub in a DB migration mode

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#228]
In order to facilitate the restoration of database dumps, the operator should be able to have blackduck instances in a "dbmigration" desiredState. 

In that state, only the postgres database container should be running and the operator shouldn't try to initialize the DB.

**Comment by rrati** [comment]
I see this as more of a 2-phase startup, where someone can opt to start the DB only, perform a migration/restore, then continue the rest of the blackduck initialiation
