### ISSUE TITLE
Skyfire lacking necessary permissions

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#23]
In order to perform tests and develop reports Skyfire needs to have more permissions for using the Kube Client. 

Skyfire Error Logging:
![image](https://user-images.githubusercontent.com/14202381/49539917-c47e5380-f89c-11e8-9b0e-ebfab94de847.png)

**Comment by mattfenwick** [comment]
@mphammer can you read through [this article on how to write bug reports](https://www.joelonsoftware.com/2000/11/08/painless-bug-tracking/) and then update this issue?  There's a lot of missing information!

**Comment by mphammer** [comment]
Skyfire is deprecated
