### ISSUE TITLE
Provide a means to download synopsysctl from the UI

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#232]
**Is your feature request related to a problem? Please describe.**
It could be useful to have a link in the UI to download synopsysctl.  This could help in situations where the operator is deployed without using synopsysctl, or where multiple users want to access the operator but only 1 used synopsysctl to deploy the operator.

**Comment by mphammer** [comment]
Due to re-architecture, this issue is no longer needed.
