### ISSUE TITLE
synopsysctl is using upstream names in options

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#260]
**What happened**:
synopsysctl is using upstream names in the options instead of the downstream names (ie perceiver vs processor).  Need to have the option names match the names used in OpsSight.

**What you expected to happen**:
Option names to correspond with the downstream OpsSight names.

**How to reproduce it (as minimally and precisely as possible)**:
synopsysctl create opssight --help

**Comment by yashbhutwala** [comment]
Fixed by #263

**Comment by rrati** [comment]
verified by synopsysctl create opssight --help and synopsysctl update opssight --help
