### ISSUE TITLE
Convert operator from RC to Deployment

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#266]
**What would you like to be added**:
Convert operator from an RC to a deployment and label it with a constant label.  Then sysnopsysctl can look for a label on a deployment instead of looking for a cluster role binding.

**Why is this needed**:
To support OLM

**Comment by mphammer** [comment]
The fix for this issue has been verified

Tests:

- `kubectl get rc -n synopsys-operator` list no resources
-  `kubectl get deployments -n synopsys-operator` listed a deployment for the synopsys-operator and for prometheus
