### ISSUE TITLE
synopsysctl cannot run on kubernetes

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#275]
**What happened**:
synopsysctl cannot run on kubernetes due to it attempting to handle routes 

**What you expected to happen**:
synopsysctl should not handle routes when on kubernetes 

**How to reproduce it (as minimally and precisely as possible)**:
./synopsysctl deploy

**Screenshots/additional context**:

**Environment (please complete the following information):**
- Kubernetes

**Comment by yashbhutwala** [comment]
Fixed by #278

**Comment by mphammer** [comment]
This issue has been verified for 2019.4.1. 

Tests:

- `synopsysctl deploy` on a GKE cluster did not fail like it previously did
- `synopsysctl deploy -e openshift` on a GKE cluster did not try to create a route, thus crdupdater knows it isn't openshift
- 'synopsysctl destroy -v debug` on a GKE cluster showed the message "kubectl exists and it isn't openshift", thus synopsysctl knows it isn't openshift
