### ISSUE TITLE
Rename prometheus options to metrics for opssight

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#281]
**What happened**:
synopsysctl has an option to enable metrics, but has additional flags to control the deployment via prometheus- options.  Should rename these options to metrics- to link with enabling metrics

**Comment by mphammer** [comment]
The fix for this issue was verified

Tests:

- `synopsysctl create opssight --help | grep prometheus` gave 0 results for flags with "prometheus"
- `synopsysctl create opssight --help | grep metrics` gave 5 flags for flags with "metrics"
- `make test` passed all tests for setting synopsysctl flags
