### ISSUE TITLE
default certificate is not used

### ISSUE THREAD

**Issue by msenmurugan** [blackducksoftware/synopsys-operator#323]
**What happened**:
 if the default cert name is specified, instead of getting the cert from synopsys-operator, it is creating a new cert each time

**What you expected to happen**:
Use the default cert

**How to reproduce it (as minimally and precisely as possible)**:
Create a Black Duck instance with default certificate name

**Comment by operator-r2d2** [comment]
@yashbhutwala: Closing this issue.

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/issues/323#issuecomment-491297894):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by yashbhutwala** [comment]
Tested and verified on openshift 3.11 via creating a new blackduck instance and checking logs
