### ISSUE TITLE
synopsysctl: Remove storage modification options from blackduck update

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#348]
**What happened**:
synopsysctl allows a user to update these options:
--persistent-storage                        Enable persistent storage
--pvc-file-path string                      Absolute path to a file containing a list of PVC json structs
--pvc-storage-class string                  Name of Storage Class for the PVC

However, changing anything storage related on a running blackduck instance would be painful at best.  Should just remove these options from update.

**What you expected to happen**:
Options not to appear

**How to reproduce it (as minimally and precisely as possible)**:
synopysctl update blackduck --help

**Comment by mphammer** [comment]
@msenmurugan @rrati Instead of removing the flags from update we can throw an error if the user tries to update persistent storage that already exists. This will allow the user to update the resource to have persistent storage later if it wasn't initially added.

**Comment by mphammer** [comment]
Implemented with PR #356
