### ISSUE TITLE
Changed operator functionality when desired state if stopped

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#375]
**What would you like to be added**:
When desired state is stop, scaled down everything to 0 as well as don't delete the PVC for both blackduck and alert.

Related to PR #357 

**Why is this needed**:
To be consistent with functionality with opssight as well as it makes more sense from a UI to not delete everything when user does stop.

**Comment by rrati** [comment]
RN-CLOUD-450
