### ISSUE TITLE
reduce CPU claim by registration container from 1 core to 0.1 cores

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#381]
Let's reduce the CPU claim of the Black Duck registration container from 1 core to 0.1 cores. The registration container does not need an entire core.

**Comment by msenmurugan** [comment]
@jdartigalongue @jbeakley whether we need to maintain the CPU core of Registration, in other words, can we remove the CPU configuration for registration server? If we remove the core configuration, whether this container will occupy more cores?
