### ISSUE TITLE
synopsysctl change to support Polaris Reporting Module

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#384]
Let's add support in synopsysctl for installing, updating, and deleting the Polaris Reporting Module.  Presumably, there would need to be commands like:

synopsysctl create rgp <options>
synopsysctl update rgp <options>
synopsysctl delete rgp <options>

Before moving ahead with this, let's get confirmation that "prm" is the right terminology.  Also need to figure out the list of configurable parameters.

**Comment by rrati** [comment]
duplicate of #245
