### ISSUE TITLE
Postgres sizes not update through synopsysctl pvc-file-path

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#391]
**What happened**:
Specifying changes to pvc values through the synopsysctl create blackduck --pvc-file-path does not change the values when the blackduck is actually created. (It is only changed in the mock)

**What you expected to happen**:
The Black Duck in the cluster has the specifications from the pvc-file-path.

**Comment by rrati** [comment]
RN-CLOUD-448

**Comment by jdartigalongue** [comment]
Tested and this issue is no longer present.
