### ISSUE TITLE
Remove console UI namespace validation

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#405]
There are some cases in which a customer may need to install Black Duck into a namespace/project that already exists. Currently, the Synopsys Operator console UI will print a warning, as it does namespace validation. We need to remove that warning.

You can see the justification for this change in the Cluster Networking section of the documentation [here](https://synopsys.atlassian.net/wiki/spaces/BDLM/pages/65765594/Black+Duck+Installation+Guide#BlackDuckInstallationGuide-networking).

**Comment by rrati** [comment]
part of #220

**Comment by VSharapov** [comment]
Do we want to skip this verification for alert and opssight too?

**Comment by rrati** [comment]
Yes.  In namespaced mode everything goes in 1 ns.

**Comment by VSharapov** [comment]
I seem to be able to deploy alerts and hubs into existing ns without issue
Closest thing to a problem is that `delete` kills the ns even if something else is in there

**Comment by msenmurugan** [comment]
I have fixed the issue for namespace scope

**Comment by rrati** [comment]
Fixed in #220
