### ISSUE TITLE
add migrate capability to synopsysctl update functionality

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#406]
secrets stored in operator, put in the corresponding crd.

**Comment by operator-r2d2** [comment]
@yashbhutwala: Closing this issue.

<details>

In response to [this](https://github.com/blackducksoftware/synopsys-operator/issues/406#issuecomment-499996005):

>/close 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
