### ISSUE TITLE
Better Function Names For Ctl Interface in Synopsysctl

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#408]
**What would you like to be added**:
1. Change names of functions to give clear functionality
2. Verify functions are correctly used throughout the code, refactor if necessary

**Why is this needed**:
It's unclear which command should perform certain functionality. (i.e. should CheckSpecFlags() or SpecIsValid() check for user input to the spec)
Commands may be incorrectly used throughout the code base.

**Comment by rrati** [comment]
NDR

**Comment by rrati** [comment]
Fixed by #706
