### ISSUE TITLE
Remove Using oc/kubectl Binaries from Synopsysctl

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#429]
**What would you like to be added**:
Remove using RunKubeCmd and RunKubeEditCmd from get, describe, and edit commands in sysnospysctl. 

**Why is this needed**:
We want to move towards native client-go usage or vendoring of native clients, vs looking for binaries. This reduces our code depending on other clients on the customer's systems.

**Comment by yashbhutwala** [comment]
Duplicates #250, probably should close one or the other, up to you @mphammer
