### ISSUE TITLE
change all synopsysctl commands to use name instead of namespace

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#431]
**What would you like to be added**:
Change all `synopsysctl COMMAND blackduck NAMESPACE [flags]` to `synopsysctl COMMAND blackduck NAME [flags]`, for all commands: `create`, `update`, `delete`, `migrate` etc.

**Why is this needed**:
To address [this comment](https://github.com/blackducksoftware/synopsys-operator/pull/390#discussion_r291703731) from PR #390 

@msenmurugan is already addressing most of this in PR #421, but just creating this issue to track/cleanup if need be after that PR gets merged.

**Comment by yashbhutwala** [comment]
Waiting for #421 to be finalized and merged.

**Comment by rrati** [comment]
Fixed by #421 and #388
