### ISSUE TITLE
Investigate Cleaner Ways of Determining Cluster Type

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#432]
**What would you like to be added**:
Investigate using (https://github.com/blackducksoftware/synopsys-operator/blob/master/pkg/util/common.go#L1367) GetKubernetesVersion() or the equivalent for Openshift to determine what cluster type is being used. 

**Why is this needed**:
The current process of determining the cluster type seems "hacky" and can cause a delay (ListRoutes will keep retrying for a period of time).

**Comment by rrati** [comment]
fixed by #364
