### ISSUE TITLE
give synopsysctl ability to push images to secure registry

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#441]
The current Synopsys Operator documentation tells customers to do the following to push the Synopsys Operator image to a secure registry:

  cd download/operator
  ./operator-images.sh --push -r <DOCKER_REGISTRY> -p <DOCKER_PROJECT> -u <DOCKER_USER>

It would be nice for synopsysctl to have the ability to do that on its own.

**Comment by rrati** [comment]
DU-CLOUD-456

**Comment by yashbhutwala** [comment]
Pushing this out of synopsysctl.  @msenmurugan please remove the script (please communicate to whoever may be potentially using it)
