### ISSUE TITLE
RabbitMQ pod repeatedly crashing

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#446]
A user is experiencing frequent crashes in the rabbitmq pod:

13:41:28.781 [error] Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only

start_error
{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
[{pid,undefined},{id,auth},{mfargs,{auth,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]
    supervisor:     errorContext:     reason:     offender: 2019-05-28 13:41:40 supervisor_report   
{local,kernel_sup}

There is additional information in this repo:
https://github.com/blackducksoftware/hub/issues/47

**Comment by jdartigalongue** [comment]
@JRVO0593 Cual versión del operador estás usando?
Esto fue solucionado en la versión 2019.6.0.
