### ISSUE TITLE
migration support from 2019.4.x to 2019.6.0

### ISSUE THREAD

**Issue by msenmurugan** [blackducksoftware/synopsys-operator#473]
Migration support from 2019.4.x to 2019.6.0

- [x] add labels to CRD
- [x] add labels to Synopsys Operator Namespace (e.g. - "synopsys.com/blackduck.bd = 2019.4.3")
- [x] Include the name field to all existing labels (e.g. name=bd)
- [x] add create by annotations to existing resources (e.g. - "synopsys.com/created.by = 2019.4.2")

**Comment by rrati** [comment]
fixed by #543
