### ISSUE TITLE
remove addpvc from synopsysctl

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#481]
Let's remove the "addpvc" command altogether.  See rrati comments, below.

Ignore the text below:
++++
Right now, we have the command:
synopsysctl update blackduck addpvc

The command "addpvc" needs to be changed to "updatepvc" (or, if it won't blow up the parsing mechanism, "update-pvc").

The change must be made because we can't add/remove PVCs from an existing Black Duck installation.  We can change the size, but we can't add or remove a PVC from a container once it starts.

Secondly, the help needs to change. It currently is:

+++
./synopsysctl update blackduck addpvc --help 
Add a Persistent Volume Claim to a Black Duck instance

Usage:
  synopsysctl update blackduck addpvc BLACK_DUCK_NAME PVC_NAME [flags]

Examples:
synopsysctl update blackduck addpvc <name> mypvc --size 2Gi --storage-class standard
synopsysctl update blackduck addpvc <name> mypvc --size 2Gi --storage-class standard -n <namespace>
+++

But this has several problems:
* addpvc should be changepvc
* "Add a Persistent" should be "Change a Persistent"
This line:
synopsysctl update blackduck addpvc BLACK_DUCK_NAME PVC_NAME [flags]
should be:
synopsysctl update blackduck changepvc \<black duck name\> \<pvc name\> [flags]

* In the examples, "mypvc" is an illegal PVC name.  it needs to match an actual Black Duck pvc name, like "blackduck-postgres".

We may also need to determine whether it is really possible to change the storage class for an existing PVC.  This may not work, so we may need to drop the "storage-class" parameter.

**Comment by rrati** [comment]
@jbeakley Actually, addpvc needs to be removed as a command all together.  We have made changes to disallow modifying PVC configuration to a running instance, but it seems this command was missing.  You shouldn't ever modify the pvc configuration of a running instance.

**Comment by rrati** [comment]
fixed by #486
