### ISSUE TITLE
synopsysctl deploy disables CRDs

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#487]
**What happened**:
 If I do `synopsysctl deploy --enable-alert -n test1` and then `synopsysctl deploy --enable-blackduck -n test2`, the second command will add the blackduck crd but also *remove* the alert crd.

**What you expected to happen**:
Both crds should be in the cluster.

**Comment by yashbhutwala** [comment]
Same issue happens when running destroy, i.e.: `synopsysctl destroy -n test1` will also delete the blackduck CRD.
