### ISSUE TITLE
Unable to change default docker registry to a private one for alpine image

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#490]
A customer(Datev e.G) wants to deploy to blackduck using images from his private registry. At the moment we use the following command to pull all images prefixed by the private registry url as stated in the document. However this still tries to pull the alpine image form docker.io. We tried a lot of things like passing blackducksoftware/alpine:latest but the only workaround is to download alpine to the local registry, go into replication controllers and update the url to use alpine image from this path. (CLOUD-422)

Code snippet here:

# Create Blackduck
./synopsysctl create blackduck blackduck --image-registries $pvt_reg/blackducksoftware/blackduck-authentication:2019.4.2,$pvt_reg/blackducksoftware/blackduck-cfssl:1.0.0,$pvt_reg/blackducksoftware/blackduck-documentation:2019.4.2,$pvt_reg/blackducksoftware/blackduck-jobrunner:2019.4.2,$pvt_reg/blackducksoftware/blackduck-logstash:1.0.4,$pvt_reg/blackducksoftware/blackduck-nginx:1.0.7,$pvt_reg/blackducksoftware/blackduck-registration:2019.4.2,$pvt_reg/blackducksoftware/blackduck-scan:2019.4.2,$pvt_reg/blackducksoftware/blackduck-solr:1.0.0,$pvt_reg/blackducksoftware/blackduck-upload-cache:1.0.8,$pvt_reg/blackducksoftware/blackduck-webapp:2019.4.2,$pvt_reg/blackducksoftware/blackduck-zookeeper:1.0.0,$pvt_reg/blackducksoftware/blackduck-postgres:1.0.7  --kubeconfig .kube/config_synopsys  -v trace

**Comment by rrati** [comment]
fixed by #498
