### ISSUE TITLE
Add support for configuring the UID/GID/FSGID of each pod. 

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#513]
**What would you like to be added**:
A new field should be added to the custom resources to configure the UID/GID/FSGID of each pod. 

**Why is this needed**:
Some k8s users may not be allowed to run containers as root.

**Comment by jayunit100** [comment]
there is an internal ticket for this - it isn't an operator level change, and requires container modifications. we can keep this open for tracking in the open.

**Comment by yashbhutwala** [comment]
Duplicates #936

**Comment by yashbhutwala** [comment]
Closing this, and tracking it in #936.  The fix in the containers will be in the Black Duck 2019.12.0, so we will incorporate synopsysctl flag also in 2019.12.0
