### ISSUE TITLE
Improve error message upon failed deploy/create/etc. due to not providing namespace

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#534]
Ran command: synopsysctl create blackduck bd2 --insecure-skip-tls-verify --size=small --persistent-storage=false --kubeconfig=/Users/joycel/Desktop/kubebinary/kubeconfig --enable-source-code-upload=true --version=2019.4.3 --admin-password=blackduck --postgres-password=blackduck --user-password=blackduck --expose-ui=NODEPORT

Error message: ERRO[0000] synopsyctl failed: namespace to create an '' instance needs to be provided 

It would be nice if we printed the type of instance that just failed to deploy/create/etc., rather than ''.

**Comment by mphammer** [comment]
Resolved in PR #559
