### ISSUE TITLE
suppress error message in 'synopsysctl edit' when no changes made

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#548]
If I run:
synopsysctl edit blackduck jb-bd
I see:
INFO[0000] editing Black Duck 'jb-bd' in namespace 'jb-bd'... 
So far, so good.

But if I then quit the file without editing, (e.g., with ":q" or ":q!"), I get this message:
ERRO[0043] synopsyctl failed: error editing Black Duck 'jb-bd' in namespace 'jb-bd' due to exit status 1 

If possible, it would be nice to suppress this spurious error message.

**Comment by mphammer** [comment]
Cannot Reproduce:
1. `./synopsysctl deploy --enable-blackduck --enable-alert --cluster-scoped`
2. `./synopsysctl create blackduck demo1 --admin-password p --postgres-password p --user-password p`
3. `./synopsysctl edit blackduck demo1` -> `:q! | :q | :wq`
```
INFO[0000] editing Black Duck 'demo1' in namespace 'demo1'... 
INFO[0003] successfully edited Black Duck 'demo1' in namespace 'demo1'...
```

**Comment by mphammer** [comment]
Cannot Reproduce: 
1. `kc create ns issuespace`
2. `./synopsysctl deploy --enable-blackduck --enable-alert -n issuespace`
3. `./synopsysctl create blackduck demo1 --admin-password p --postgres-password p --user-password p -n issuespace`
4. `./synopsysctl edit blackduck demo1 -n issuespace`
```
INFO[0000] editing Black Duck 'demo1' in namespace 'issuespace'... 
INFO[0002] successfully edited Black Duck 'demo1' in namespace 'issuespace'... 
```
