### ISSUE TITLE
in cluster-scope operator, don't require providing namespace when updating black duck

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#550]
If you install Synopsys Operator with cluster scope, and then install Black Duck in a namespace that differs from the Black Duck name, don't require the user to specify both the name and the namespace when running the "synopsysctl update blackduck" command.

Here's how to reproduce this problem:

1) Install Synopsys Operator with cluster scope
2) Install Black Duck where the name is different from the namespace.  For example:

sc create blackduck jb-bd --namespace jbbdns

3) Now, try to update the Black Duck instance without specifying the namespace, for example:

sc update blackduck jb-bd --expose-ui NODEPORT

The command above will fail with the message:
ERRO[0000] synopsyctl failed: unable to get jb-bd namespace due to namespaces "jb-bd" not found 

The problem here is that synopsysctl is assuming that in cluster scope, the Black Duck name and namespace will be the same, but that isn't always going to be the case.

**Comment by rrati** [comment]
How would you want this to behave?  When creating the instance the ns name will be the same as the app name unless you provide a --namespace parameter.  update is working under the same pretext.

**Comment by jbeakley** [comment]
I just want:
synopsysctl update blackduck <name> --expose-ui NODEPORT
to work.

synopsysctl should be able to deduce the namespace from the name, so let's not make the user provide it every time they want to update the black duck instance.

The documentation is getting a little complicated regarding when to tell the user whether to specify the namespace... it would be easier to just say: specify the namespace in namespace scope, and you don't have to in cluster scope.

**Comment by rrati** [comment]
It would work automatically if you didn't provide a different ns when you created it.  This is standard kubernetes procedure when issuing commands for a specific namespace, ie most commands.  We could do some searching of ns to find the app in theory, but that isn't implemented atm.

**Comment by msenmurugan** [comment]
@rrati 

I think, already https://github.com/blackducksoftware/synopsys-operator/blob/master/pkg/synopsysctl/utils.go#L244:L263 should cover this scenario
