### ISSUE TITLE
`synopsysctl update blackduck <bd_name> --liveness-probes=true` does not enable liveness probes

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#560]
hub version: 2019.6.0
operator version: 2019.6.0

Steps:
1. Deploy operator w/ namespace-scope.
2. Create a hub in the same namespace as operator, w/out liveness probes enabled. Wait for the hub to finish creating.
3. Run the following: synopsysctl update blackduck <bd_name> --liveness-probes=true -n <NAMESPACE>.

The pods are not restarted and when running 'kubectl describe pod' on the pods, I don't see any liveness info.

When running 'kubectl -n NAMESPACE get blackduck <blackduck_name> -o yaml', I do see livenessProbes: true though.

**Comment by rrati** [comment]
fixed by #602
