### ISSUE TITLE
synopsysctl native should only require DB credentials with --output-database 

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#563]
**How to reproduce it (as minimally and precisely as possible)**:
./synopsysctl create blackduck native  test
ERRO[0000] synopsyctl failed: required flag(s) "admin-password", "postgres-password", "user-password" not set

**Comment by msenmurugan** [comment]
@jdartigalongue admin password and user password is required to generate the postgres db-cred secret.

**Comment by mphammer** [comment]
Only require the passwords if creating the Black Duck Native Database resources. Do not require if creating only the Black Duck Native CRD resources or the Black Duck Native PVC resources.
