### ISSUE TITLE
synopsysctl accepts invalid values for --target

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#564]
**How to reproduce it (as minimally and precisely as possible)**:

./synopsysctl create blackduck native  --external-postgres-admin test --external-postgres-admin-password test --external-postgres-host test --external-postgres-port 5432 --external-postgres-user test --external-postgres-user-password test --external-postgres-ssl false  --target **test**  test

**Comment by mphammer** [comment]
Resolved by PR #571
