### ISSUE TITLE
synopsysctl native should print the supported versions if an invalid version is specified

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#565]
**What would you like to be added**:
There is currently no way to know which version of Blackduck synopsysctl supports without looking at the code. 

./synopsysctl create blackduck native  --admin-password test --postgres-password test --user-password test --version 222  test
ERRO[0000] synopsyctl failed: failed to get components: version '222' is not supported

**Comment by yashbhutwala** [comment]
Closed by #597
