### ISSUE TITLE
Synopsysctl handles PVCs for --mock and Native

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#579]
**What happened**:
Resources cannot be easily created when running in MockMode or using Native resources due to synopsyctl not creating PVCs for the Synopsys resources. 

**What you expected to happen**:
Synopsyctl should give the user the ability to generate PVC resources when running in Native mode. 
Synopsysctl should warn the user that PVCs are not supported in --mock mode or it should allow the user to generate templates for them. 

**How to reproduce it (as minimally and precisely as possible)**:
./synopsysctl deploy cluster-scoped --enable alert
./syopsysctl create alert alt --mock json > alt.json
kubectl create -f alt.json

You will see an Error event like `persistentvolumeclaim "alt-alert-alert-pvc" not found`

**Comment by rrati** [comment]
fixed by #588 and #562
