### ISSUE TITLE
Add validation directly into a CRD

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#617]
**What would you like to be added**:
Add validation logic directly into each of CRDs.

**Why is this needed**:
If a customer wants to use yaml for their custom resource, they can use it without messing it up.  We can have validation built-in for each of the Spec Fields.

CRDs support [validation](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation) by defining an [OpenAPI v3 schema](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject) or [ValidatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook) in the validation section.

**Comment by msenmurugan** [comment]
@yashbhutwala Already we have the validation admission webhook in place. Just we need to add all validations. And also, it's not enabled by default for certain Kubernetes version.

**Comment by yashbhutwala** [comment]
Closing, due to not using CRD in future.
