### ISSUE TITLE
Increase memory for registration service for x-large deployments

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#625]
When deploying an "x-large" Black Duck instance with Synopsys Operator, the registration container entered a crash backoff loop. It would appear that the current value of "640 MB" of memory is not sufficient to handle the registration requests of the increased number of job runners and scanners in an x-large deployment. Increasing to 1 Gig should solve the problem.

**Comment by rrati** [comment]
fixed by #644
