### ISSUE TITLE
Synopsysctl doesn't add values from GetAlertDefault() if some envs were specified using  --environs

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#627]
**What happened**:
Alert was unable to start

**What you expected to happen**:
Synopsysctl or the operator should have automatically added 
PUBLIC_HUB_WEBSERVER_HOST:localhost
PUBLIC_HUB_WEBSERVER_PORT:443
ALERT_SERVER_PORT: 8443

**How to reproduce it (as minimally and precisely as possible)**:
/synopsysctl create alert alert3 --environs="HUB_CFSSL_HOST:alert3-alert-cfssl" --mock  yaml

**Comment by yashbhutwala** [comment]
@jdartigalongue is this still an open issue?  If so, which milestone do we want this for?
