### ISSUE TITLE
Support cross-namespace resource management with a single operator

### ISSUE THREAD

**Issue by yashbhutwala** [blackducksoftware/synopsys-operator#628]
**Why is this needed**:

As of `2019.6.0`, in namespaced mode, operator has to be installed in every namespace that a customer wants to run resources.  In cluster mode, only one operator can be installed, but it requires privileged permissions for all namespaces, which may not be suitable for all customers.  While these two supported scenarios may cover most customers' needs, I think having only one operator in the cluster, which has user-defined restrictions as far as what namespaces it can control could be potentially helpful.  This makes it simpler for a customer to upgrade/migrate an operator because they only have to upgrade one, and at the same time, they don't have to give the operator cluster-wide `[create delete get list patch update watch]` permissions, where they may have their proprietary software running.  This can also allow a separation of duties: as one team can be responsible for managing the configuration of the operator (upgrade, migrate, etc.), and other specific teams can be responsible for blackduck, alert, etc. synopsys products.  

Currently, at least to my understanding, in Kubernetes, `serviceaccounts`, `roles` and `rolebindings` are namespaced, so we'd have to define one `clusterroles` that allows access and then create a `rolebindings` to that `clusterroles` in each user desired namespace.  Also, I think we'd have to have the cr controllers be able to launch watch events per namespace per resource.

Perhaps not in scope of this ticket, but also kind of related: make a single operator be able to run cross-cluster, and manage resources in multiple clusters. Perhaps, that's even more of a rare use-case, but may be a cool feature to add in the future.

**Comment by mphammer** [comment]
I think this is an awesome idea! Also we could consider breaking each of the controllers into their own pods and then have Synopsys Operator manage them (i.e. create more as they are needed).

**Comment by yashbhutwala** [comment]
I did a little more digging around why doing a single watch on n number of namespaces is not supported server side (currently only either a single ns watch or a ns all watch), and I found this upstream issue that is of interest: https://github.com/kubernetes/kubernetes/issues/74415.  Looks like `prometheus-operator` is already doing this.

**Comment by yashbhutwala** [comment]
Also relevant is the discussion about multi-tenancy and operatorGroups here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-wg-multitenancy/Jzaty0FLiy0/yaVJ6RpbCAAJ

**Comment by yashbhutwala** [comment]
Will not be worked on.
