### ISSUE TITLE
create a 'synopsys describe operator' command

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#633]
One you deploy the operator, there is no easy way for customers to determine:
* what scope Operator was deployed with
* what products (black duck, alert, opssight) were enabled when Operator was deployed

It would be nice to have a:
synopsysctl describe operator
command that tells you these things.

I request this because I can see how a customer might get confused about what permissions they have and what products they can deploy.

**Comment by yashbhutwala** [comment]
closing this.
