### ISSUE TITLE
support annotations for custom load balancers

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#637]
Some users of Synopsys Operator may not use the default Kubernetes load balancer in their clusters. For added control and security, some users may create custom load balancers that require services to have a particular annotation before they can be exposed outside the cluster.

It would be nice to have a feature in Synopsys Operator that allowed the user to pass this annotation to synopsysctl/operator, such that if the user attempts to expose the Black Duck UI (or the console UI) with a loadbalancer, the proper annotation could be automatically added to the proper service.

Additionally, we'd want Synopsys Operator to respect/retain annotations made manually by users so that Synopsys Operator does not delete the annotations during product upgrades.

**Comment by yashbhutwala** [comment]
Supported by native.
