### ISSUE TITLE
Gracefully handle misconfiguration

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#684]
**What would you like to be added**:
Currently the operator has a hard timeout of 10 minutes waiting for applications to come up.  If an application won't come up because of a misconfiguration then there is no way to fix it until that 10 minute timeout has expired.  Would be better to handle updates on a CRD and re-start the wait cycle so fixes can be applied faster.

**Why is this needed**:
Better user experience when trying to fix misconfigurations

**Comment by rayflexera** [comment]
Ref: RN-cloud-448
