### ISSUE TITLE
--encryption-global-salt and --encryption-password should be mandatory when deploying alert  

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#707]
Alert requires both the salt and encryption but the `--encryption-global-salt ` and `--encryption-password` are not mandatory in synopsysctl

**Comment by rrati** [comment]
RN-CLOUD-448

**Comment by jdartigalongue** [comment]
As per the Alert documentatiom, settings those ALERT_ENCRYPTION_PASSWORD and ALERT_ENCRYPTION_GLOBAL_SALT via env is now optional since it can also be configured through the user interface.  Closing the ticket.
