### ISSUE TITLE
Support for 2019.8.0 Black Duck and multiple hubs in the same namespace

### ISSUE THREAD

**Issue by msenmurugan** [blackducksoftware/synopsys-operator#716]
**What would you like to be added**:
Support for 2019.8.0 Black Duck and multiple hubs in the same namespace

**Why is this needed**:
It will be useful for customers to have multiple hubs in the same namespace

**Comment by rayom81** [comment]
RN-CLOUD-448

**Comment by rrati** [comment]
UI fixed by #769
