### ISSUE TITLE
Add flag to configure image-registries

### ISSUE THREAD

**Issue by calvin-blackduck** [blackducksoftware/synopsys-operator#726]
**What would you like to be added**:
Add a flag to allow the --image-registries option in synopsysctl operator to accept path to the root folder of docker registry where all images are stored 

**Why is this needed**:
So users do not have to specify the complete path to each image.

Example:
--image-registries <docker-registry-host>/blackduck
Instead of:
--image-registries gcr.io/blackducksoftware/blackduck-cfssl:2019.4.1,gcr.io/blackducksoftware/blackduck-nginx:1.0.7"

**Comment by msenmurugan** [comment]
@jdartigalongue @rrati it's time to add Registry Configuration in the list of flags :-)

**Comment by rrati** [comment]
DU-CLOUD-464

**Comment by jlin963** [comment]
Verified in OS4; used new --registry flag + the --version flag to cover most of the images, then used --image-registries to specify images for postgres, cfssl, and rabbitmq (since these 3 don't follow the black duck version, e.g. 2019.8.0).
