### ISSUE TITLE
Remove namespace from cluster CRs

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#730]
**What happened**:
Kubernetes issued a fix for 
https://seclists.org/oss-sec/2019/q3/117

Which means any cluster level CR with a namespace field will be rejected.

**What you expected to happen**:
Cluster level operator should function properly

**How to reproduce it (as minimally and precisely as possible)**:
Create an application when running in cluster mode.

**Comment by jlin963** [comment]
Still occurring, seeing this in operator logs:

`time="2019-08-23T17:26:18Z" level=debug msg="ObjectUpdated: bd2"
time="2019-08-23T17:26:18Z" level=debug msg="ObjectUpdated: bd1"
time="2019-08-23T17:26:29Z" level=debug msg="attempting to open db host bd2-blackduck-postgres.bd1.svc.cluster.local for database postgres"
time="2019-08-23T17:26:29Z" level=debug msg="connected to db host bd2-blackduck-postgres.bd1.svc.cluster.local for database postgres"
time="2019-08-23T17:26:29Z" level=debug msg="attempting to open db host bd1-blackduck-postgres.bd1.svc.cluster.local for database postgres"
time="2019-08-23T17:26:29Z" level=debug msg="connected to db host bd1-blackduck-postgres.bd1.svc.cluster.local for database postgres"
time="2019-08-23T17:26:50Z" level=error msg="the server could not find the requested resource (put blackducks.synopsys.com bd2)"
time="2019-08-23T17:26:50Z" level=info msg="Controller.runWorker: processing next item"
time="2019-08-23T17:26:50Z" level=info msg="Controller.processNextItem: start"
time="2019-08-23T17:26:50Z" level=error msg="the server could not find the requested resource (put blackducks.synopsys.com bd1)"`
