### ISSUE TITLE
I need a way for operator to print what versions are supported.

### ISSUE THREAD

**Issue by rpiskule-syn** [blackducksoftware/synopsys-operator#777]
**What would you like to be added**:
The ability for Operator to list out supported versions of Blackduck / Alert.

**Why is this needed**:
Because we heavily use the Customer Resource feature of Operator, it is necessary for us to have a way of preventing a user from trying to alter a Hub to use a version of Hub that doesn't exist.

For further details, contact me directly.

**Comment by jdartigalongue** [comment]
@rpiskule-syn  Here is a workaround until we find a better way to list the supported versions: 

```/synopsysctl create blackduck native test --version test --admin-password test --postgres-password test --user-password test
ERRO[0000] synopsyctl failed: failed to get components: version 'test' is not supported.  Supported versions: 2019.2.2, 2018.12.0, 2018.12.1, 2018.12.2, 2018.12.3, 2018.12.4, 2019.2.0, 2019.2.1, 2019.6.2, 2019.6.1, 2019.6.0, 2019.4.0, 2019.4.1, 2019.4.2, 2019.4.3, 2019.8.0```

**Comment by yashbhutwala** [comment]
Closing because duplicated issue.
