### ISSUE TITLE
Support getting available versions of app

### ISSUE THREAD

**Issue by rrati** [blackducksoftware/synopsys-operator#785]
**What would you like to be added**:
The operator will talk to a server to get a list of apps and versions that are supported.  Should provide a way to load this data into the operator/synopsysctl for users w/o direct access to the internet.

**Why is this needed**:
Operator won't know about new apps or versions without direct access to the internet without this.

**Comment by yashbhutwala** [comment]
Change this into "Versions supported by synopsysctl are: XYZ" instead of "404 not found"

**Comment by yashbhutwala** [comment]
Need to add a file in top level app matching to versions

**Comment by yashbhutwala** [comment]
Resolved by #1083
