### ISSUE TITLE
cleanup resources created by polaris operator

### ISSUE THREAD

**Issue by adityabyreddy74** [blackducksoftware/synopsys-operator#847]
Some of the k8s resources are being created by the custom tools at runtime. Have a feature to cleanup these resources to keep further deployments going inconsistent.

**List of resources being created independent of operator**

secret/auth-client-tls-certificate
secret/auth-server-tls-certificate
secret/swip-eventstore-admin-creds
secret/swip-eventstore-creds
secret/swip-eventstore-reader-creds
secret/swip-eventstore-writer-creds
secret/swip-tools-minio
secret/swip-upload-server
secret/tds-code-analysis-tls-certificate
secret/vault-ca-certificate
secret/vault-init-secret
secret/vault-tls-certificate

**Comment by yashbhutwala** [comment]
Resolved by @jdartigalongue
