### ISSUE TITLE
Investigate Providing Ability to Set the Name of Polaris

### ISSUE THREAD

**Issue by mphammer** [blackducksoftware/synopsys-operator#860]
**What would you like to be added**:

Right now there can only be one instance of Polaris in the cluster. Thus, there is no need for synopsysctl to be able to set the name of the Polaris instance. 

We should determine if providing a name for Polaris is useful?
- Consistency to other synopsysctl commands `./ctl create <resource> <name>`
- Will there ever be multiple instances?
- What if there is another product named Polaris?

**Comment by yashbhutwala** [comment]
Currently, we are only supporting polaris per namespace, and we are storing the configuration in a secret.  Since we're not creating a crd, we don't need to worry about another product named Polaris.
