### ISSUE TITLE
Would like to be able to output mock pvcs

### ISSUE THREAD

**Issue by nichollsdave** [blackducksoftware/synopsys-operator#868]
**What would you like to be added**:
If you want to list pvcs by using --mock json then it doesn't list the pvcs.  If you pass in --postgres-claim-size it will list the pvc for postgres but no other pvcs.  This is expected but it is useful to be able to output the required configuration without actually creating and running a Black Duck.  

**Why is this needed**:
Customer is trying to troubleshoot pvcs that are created due to a bug in Operator and would like to output the mock pvcs to create them manually.

**Comment by mphammer** [comment]
Synopsysctl needs to print the pvc names for a given app and probably their default sizes
