### ISSUE TITLE
migration-mode causes postgres to constantly restart - making it difficult to populate the database

### ISSUE THREAD

**Issue by nichollsdave** [blackducksoftware/synopsys-operator#873]
**What happened**:
Attempting to start Black Duck in migration-mode to populate the database from a backup.  However when doing this the postgres pod continually restarts (despite it running successfully), I cannot work out why it continually restarts.  This was reported by a customer and reproduced by myself.

**What you expected to happen**:
When using --migration-mode I expect the postgres pod to start and stay started so I can populate the data

**How to reproduce it (as minimally and precisely as possible)**:
./synopsysctl create blackduck test-bd --expose-ui LOADBALANCER --admin-password blackduck --postgres-password blackduck --user-password blackduck --persistent-storage=true --pvc-storage-class managed-premium --pvc-file-path pvcs.json --migration-mode

Then 'watch kubectl get pods -n test-bd' and see that the pod starts and restarts repeatedly.

**Environment (please complete the following information):**
- Kubernetes version (use `kubectl version`): 1.13.10
- Cloud provider or hardware configuration: AKS

**Comment by nichollsdave** [comment]
Note this is Operator 2019.8.3

**Comment by rrati** [comment]
@nichollsdave Can you provide the contents of the pvcs.json as well?

**Comment by nichollsdave** [comment]
I can but it is not related to that, this also happens on AWS EC2 and seems to restart every 2 mins :

{
"Data": [           
		   {
              "name": "test-bd-blackduck-authentication",
              "size": "2Gi"                      
           },
		   {
              "name": "test-bd-blackduck-registration",
              "size": "2Gi"                      
           },
		   {
              "name": "test-bd-blackduck-uploadcache-data",
              "size": "100Gi"                      
           },
		   {
              "name": "test-bd-blackduck-postgres",
              "size": "200Gi"                      
           },
		   {
              "name": "test-bd-blackduck-cfssl",
              "size": "2Gi"                      
           },
		   {
              "name": "test-bd-blackduck-solr",
              "size": "2Gi"                      
           },
		   {
              "name": "test-bd-blackduck-webapp",
              "size": "2Gi"                      
           },
		   {
              "name": "test-bd-blackduck-logstash",
              "size": "20Gi"                      
           },
		   {
              "name": "test-bd-blackduck-zookeeper",
              "size": "4Gi"                      
           } 		   
        ]
}
