### ISSUE TITLE
tar -xvf for instructions 

### ISSUE THREAD

**Issue by jayunit100** [blackducksoftware/synopsys-operator#93]
The wiki for installation sais

```
Uncompress and un-tar the downloaded file:

gunzip 2019.1.0.tar.gz
tar -xvf 2019.1.0.tar
```

instead,  just do `tar -xvf 2019.1.0.tar.gz`

**Comment by jbeakley** [comment]
@jayunit100 , could you please create a JIRA ticket?  Kidding.  I made the change.
