### ISSUE TITLE
CRD updater

### ISSUE THREAD

**Issue by msenmurugan** [blackducksoftware/synopsys-operator#95]
- [x] Support patch for Cluster roles

- [x] Support patch for Services

- [x] Include RoleRef during the Cluster role binding patch method

- [x] Add binary data comparison for config map

**Comment by msenmurugan** [comment]
@rrati Is there any use case for patching service account? Can I remove it from the list?

**Comment by rrati** [comment]
I'm not sure there is.  I'm fine removing it for now.

**Comment by msenmurugan** [comment]
The Service account patch will be done in future if it is required
