### ISSUE TITLE
OpsSight service exposed not working using NODEPORT

### ISSUE THREAD

**Issue by msenmurugan** [blackducksoftware/synopsys-operator#970]
**What happened**:
OpsSight service that are exposed using NODEPORT is not working

**What you expected to happen**:
Need to access the prometheus metrics and opssight model using NODEPORT

**How to reproduce it (as minimally and precisely as possible)**:
Create a opssight with --enable-metrics true and --expose-metrics NODEPORT

**Comment by yashbhutwala** [comment]
Fixed by commit `ccc5b14b614f6de06e004e98d89b1eca028571fc`
